const UI_HOME_TAG_SWITCH = 'UI_HOME_TAG_SWITCH';

const UI_USER_LIST_SWITCH = 'UI_USER_LIST_SWITCH';

const UI_ACTIVITY_SHOW = 'UI_ACTIVITY_SHOW';

const UI_ACTIVITY_HIDE = 'UI_ACTIVITY_HIDE';

const UI_USER_DETAIL_SHOW = 'UI_USER_DETAIL_SHOW';

const UI_USER_DETAIL_HIDE = 'UI_USER_DETAIL_HIDE';

const UI_ACTIVITY_SET = 'UI_ACTIVITY_SET';

const UI_ADMIN_PANEL_SWITCH = 'UI_ADMIN_PANEL_SWITCH';

const UI_ADMIN_FORM_TYPE_SWITCH = 'UI_ADMIN_FORM_TYPE_SWITCH';

const UI_ADMIN_SET = 'UI_ADMIN_SET';

const UI_LOADING = 'UI_LOADING';

const UI_LOADING_HIDE = 'UI_LOADING_HIDE';

const UI_DRAWER_SHOW = 'UI_DRAWER_SHOW';

const UI_DRAWER_HIDE = 'UI_DRAWER_HIDE';

const UI_SELECTED_USER_LIST = 'UI_SELECTED_USER_LIST';

const UI_SHOW_LOGIN = 'UI_SHOW_LOGIN';

const UI_SHOW_RESET_PASSWORD = 'UI_SHOW_RESET_PASSWORD';

const UI_HIDE_RESET_PASSWORD = 'UI_HIDE_RESET_PASSWORD';

const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';

const ACCOUNT_RESET = 'ACCOUNT_RESET';

const ACTIVITY_LIST_SET = 'ACTIVITY_LIST_SET';

const ADMIN_LIST_SET = 'ADMIN_LIST_SET';

const USER_LIST_SET = 'USER_LIST_SET';

const NOTICE_NEW_USERS_SET = 'NOTICE_NEW_USERS_SET';

export const ACTION_TYPES = {
    UI_HOME_TAG_SWITCH,
    UI_USER_LIST_SWITCH,
    UI_ACTIVITY_SHOW,
    UI_ACTIVITY_HIDE,
    UI_ACTIVITY_SET,
    UI_ADMIN_PANEL_SWITCH,
    UI_ADMIN_FORM_TYPE_SWITCH,
    UI_ADMIN_SET,
    UI_DRAWER_SHOW,
    UI_DRAWER_HIDE,
    UI_USER_DETAIL_SHOW,
    UI_USER_DETAIL_HIDE,
    UI_SELECTED_USER_LIST,
    UI_SHOW_LOGIN,
    UI_SHOW_RESET_PASSWORD,
    UI_HIDE_RESET_PASSWORD,
    ACCOUNT_LOGOUT,
    ACCOUNT_LOGIN,
    ACCOUNT_RESET,
    ACTIVITY_LIST_SET,
    ADMIN_LIST_SET,
    USER_LIST_SET,
    UI_LOADING,
    UI_LOADING_HIDE,
    NOTICE_NEW_USERS_SET
}

