"""migration with user_document table.

Revision ID: 062e9ca76e88
Revises: 186dd5501b6c
Create Date: 2023-06-28 12:07:39.960130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062e9ca76e88'
down_revision = '186dd5501b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identity_documents',
    sa.Column('openid', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('id_document_reverse_side', sa.BLOB(), nullable=True, comment='用户身份证人像面（背面）'),
    sa.Column('id_document_obverse_side', sa.BLOB(), nullable=True, comment='用户身份证国徽面（正面）'),
    sa.PrimaryKeyConstraint('openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identity_documents')
    # ### end Alembic commands ###
