"""empty message

Revision ID: 186dd5501b6c
Revises: f52b2221293b
Create Date: 2021-11-05 01:12:26.069142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186dd5501b6c'
down_revision = 'f52b2221293b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust.! ###
    op.add_column('activity_participant', sa.Column('sign_method', sa.String(length=10), nullable=True, comment='签到方式：token, gps=default'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_participant', 'sign_method')
    # ### end Alembic commands ###
