"""Add column to activity - theme_pic_name

Revision ID: 555dd411434a
Revises: 7842ebe38a79
Create Date: 2021-07-12 14:50:59.831349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '555dd411434a'
down_revision = '7842ebe38a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('theme_pic_name', sa.String(100), nullable=False,
                                        comment='Activity theme picture, save to /static/activity_theme_picture/*'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'theme_pic_name')
    # ### end Alembic commands ###
