"""Add sign in token

Revision ID: 7842ebe38a79
Revises: 9c349bdbae17
Create Date: 2021-07-11 02:34:59.018055

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7842ebe38a79'
down_revision = '9c349bdbae17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('sign_in_token', sa.String(10), nullable=False, comment='Sign in token.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'sign_in_token')
    # ### end Alembic commands ###
