"""change them pic column length & add column avatar url

Revision ID: a4dce2e22aa3
Revises: a602d31f78e1
Create Date: 2021-08-05 10:12:21.884038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4dce2e22aa3'
down_revision = 'a602d31f78e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(300), nullable=False,
                                    comment='User avatar url'))
    op.alter_column('activity',
                    column_name='theme_pic_name',
                    existing_type=sa.String(300))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.alter_column('activity',
                    column_name='theme_pic_name',
                    existing_type=sa.String(100))
    # ### end Alembic commands ###
