"""modify column name

Revision ID: a602d31f78e1
Revises: 555dd411434a
Create Date: 2021-07-20 12:30:27.662168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a602d31f78e1'
down_revision = '555dd411434a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_participant',
                    column_name='certiticate_date',
                    existing_type=sa.DateTime(),
                    new_column_name='certificate_date')
    # op.drop_constraint('user_pkey', 'users', type_='primarykey')
    # op.create_primary_key('user_pkey', 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_participant',
                    column_name='certificate_date',
                    existing_type=sa.DateTime(),
                    new_column_name='certiticate_date')
    # ### end Alembic commands ###
