"""modify column length

Revision ID: b5d7ace58689
Revises: a4dce2e22aa3
Create Date: 2021-08-05 10:23:04.494308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5d7ace58689'
down_revision = 'a4dce2e22aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity',
                    column_name='theme_pic_name',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=sa.String(length=300))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity',
                    column_name='theme_pic_name',
                    existing_type=mysql.VARCHAR(length=300),
                    type_=sa.String(length=100))
    # ### end Alembic commands ###
