"""1.init

Revision ID: f52b2221293b
Revises: 
Create Date: 2021-09-30 04:14:34.943150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52b2221293b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False, comment='管理员账户创建日期,创建新管理员时自动生成'),
    sa.Column('password', sa.String(length=60), server_default='0', nullable=False, comment='管理员账户密码哈希串,创建管理员输入密码或管理员更新密码时自动生成'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='管理员姓名,由`root`用户或管理员更新信息时输入'),
    sa.Column('email', sa.String(length=32), nullable=True, comment='管理员账户邮箱地址, 创建管理员账户时输入，验证完成之后即为管理员登录账户名'),
    sa.Column('email_verified', sa.Integer(), server_default='0', nullable=True, comment='邮箱验证标识位，0=未验证，1=已验证, 新用户在邮件中点击确认认证后设置'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pickup_impaired',
    sa.Column('openid', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='活动ID'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='真实姓名'),
    sa.Column('id_no', sa.String(length=18), nullable=True, comment='身份证号码（18位）'),
    sa.Column('impaired_no', sa.String(length=20), nullable=True, comment='残疾证编号'),
    sa.Column('pickup_addr', sa.String(length=256), nullable=True, comment='接送的起始位置'),
    sa.Column('emergency_contact', sa.String(length=32), nullable=True, comment='紧急联系人电话'),
    sa.Column('pickup_method', sa.String(length=32), nullable=True, comment='该视障人士被接送的方式'),
    sa.Column('pickup_volunteer_openid', sa.String(length=64), nullable=True, comment='该视障人士被接送的志愿者用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('openid', 'activity_id')
    )
    op.create_table('pickup_volunteer',
    sa.Column('openid', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='活动ID'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='真实姓名'),
    sa.Column('id_no', sa.String(length=18), nullable=True, comment='身份证号码'),
    sa.Column('pickup_addr', sa.String(length=512), nullable=True, comment='志愿者所在的区域，系统会根据志愿者所在区域就近安排'),
    sa.Column('provide_service', sa.String(length=32), nullable=True, comment='支援者登记可以提供的志愿者服务（如接视障人士参加活动、送视障人士回家等等），含具体可提供的接送方式'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('openid', 'activity_id')
    )
    op.create_table('user',
    sa.Column('openid', sa.String(length=28), nullable=False, comment='用户表主键值，用于索引，字串由微信生成，对于同一小程序，不同微信用户的openid不相同'),
    sa.Column('registration_date', sa.DateTime(), nullable=False, comment='用户账户申请日期,新用户申请账户时生成'),
    sa.Column('role', sa.Integer(), server_default='0', nullable=False, comment='用户类型, 0=志愿者, 1=视障人士,新用户申请账户时设定'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='用户姓名,用户申请账户时输入，可更新'),
    sa.Column('real_name', sa.String(length=100), nullable=True, comment='用户真实姓名,用户申请证书时输入，可更新'),
    sa.Column('id_type', sa.String(length=100), nullable=True, comment='证件类型：身份证；护照；驾驶证等,用户申请证书时输入，可更新'),
    sa.Column('idcard', sa.String(length=18), nullable=True, comment='用户18位身份证号,用户申请账户时输入，可选'),
    sa.Column('idcard_verified', sa.Integer(), server_default='0', nullable=True, comment='身份证号验证标识位，0=未验证，1=已验证,待引用'),
    sa.Column('disabled_id', sa.String(length=60), nullable=True, comment='视障人士残疾人证号,视障人士申请账户时输入'),
    sa.Column('disabled_id_verified', sa.Integer(), server_default='0', nullable=True, comment='残疾人证号验证标识位，0=未验证，1=已验证,待引用'),
    sa.Column('phone', sa.String(length=16), nullable=False, comment='用户联系电话,用户申请账户时输入，可更新'),
    sa.Column('phone_verified', sa.Integer(), server_default='0', nullable=False, comment='联系电话验证标识位，0=未验证，1=已验证,用户申请账户时需先认证联系电话'),
    sa.Column('email', sa.String(length=32), nullable=True, comment='用户邮箱'),
    sa.Column('email_verified', sa.Integer(), server_default='0', nullable=True, comment='用户邮箱验证标识位，0=未验证，1=已验'),
    sa.Column('contact', sa.String(length=16), nullable=True, comment='用户备用联系电话,用户申请账户时输入，可选，可更新'),
    sa.Column('gender', sa.String(length=1), server_default='无', nullable=False, comment='用户性别，"男"或者"女",用户申请账户时输入，可更新'),
    sa.Column('birth', sa.DateTime(), nullable=False, comment='用户生日,用户申请账户时输入，可更新'),
    sa.Column('address', sa.String(length=80), server_default='无', nullable=True, comment='用户联系地址,用户申请账户时输入，可更新'),
    sa.Column('emergent_contact', sa.String(length=8), nullable=True, comment='视障人士紧急联系人姓名,视障人士申请账户时输入，可更新'),
    sa.Column('emergent_contact_phone', sa.String(length=16), nullable=True, comment='视障人士紧急联系人联系电话,视障人士申请账户时输入，可更新'),
    sa.Column('activities_joined', sa.Integer(), server_default='0', nullable=False, comment='微信端显示活动参加次数，以及根据次数计算参加时长,待定'),
    sa.Column('remark', sa.String(length=255), server_default='无', nullable=True, comment='用户备注,用户申请账户时输入'),
    sa.Column('audit_status', sa.Integer(), server_default='0', nullable=False, comment='用户注册申请的审核状态,0=进行中, 1=已通过, -1=被拒绝,2=导入数据,管理员审核注册用户时更新'),
    sa.Column('push_status', sa.Integer(), server_default='0', nullable=False, comment='???'),
    sa.Column('recipient_name', sa.String(length=100), nullable=True, comment='证书收件人姓名,用户申请证书时输入，可更新'),
    sa.Column('recipient_address', sa.String(length=80), nullable=True, comment='证书收件人地址,用户申请账户时输入，可更新'),
    sa.Column('recipient_phone', sa.String(length=16), nullable=True, comment='证书收件人电话,用户申请账户时输入，可更新'),
    sa.Column('avatar_url', sa.String(length=300), nullable=False, comment='用户微信头像地址链接'),
    sa.PrimaryKeyConstraint('openid'),
    sa.UniqueConstraint('disabled_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('idcard'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='活动表主键ID，用于索引,系统内部可见，数据库自动从1开始自增'),
    sa.Column('title', sa.String(length=60), nullable=False, comment='活动标题,发布活动时输入'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='活动开始时间,发布活动时输入'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='活动地点,发布活动时输入'),
    sa.Column('location_latitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='活动地点纬度'),
    sa.Column('location_longitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='活动地点经度'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='活动结束时间,发布活动时输入，可选'),
    sa.Column('content', sa.String(length=4000), nullable=False, comment='活动内容,发布活动时输入'),
    sa.Column('notice', sa.String(length=4000), nullable=True, comment='活动注意事项，发布活动时输入，可选'),
    sa.Column('others', sa.String(length=120), server_default='无', nullable=False, comment='活动其他相关内容，发布活动时输入'),
    sa.Column('admin_raiser', sa.Integer(), nullable=True, comment='活动创建者，如果是管理员创建则使用该域，创建活动项时系统自动设置'),
    sa.Column('user_raiser', sa.String(length=28), nullable=True, comment='活动创建者，如果是视障人士/志愿者用户则使用该域，创建活动项时系统自动设置'),
    sa.Column('approver', sa.Integer(), nullable=True, comment='活动审批者,管理员审批活动时更新'),
    sa.Column('assignee', sa.String(length=28), nullable=True, comment='活动领队/负责人,待定'),
    sa.Column('published', sa.Integer(), server_default='0', nullable=False, comment='活动审核发布标志位, 0=未审核，1=已审核,管理员审核活动时更新'),
    sa.Column('tag_ids', sa.String(length=120), nullable=True, comment='活动分类标签,管理员审核活动时更新'),
    sa.Column('volunteer_capacity', sa.Integer(), server_default='0', nullable=True, comment='所需志愿者人数'),
    sa.Column('vision_impaired_capacity', sa.Integer(), server_default='0', nullable=True, comment='活动可容纳最大视障者人数'),
    sa.Column('volunteer_job_title', sa.String(length=500), nullable=True, comment='对应发布新活动时表单上的岗位名称'),
    sa.Column('volunteer_job_content', sa.String(length=100), nullable=True, comment='对应发布新活动时表单上的岗位人数'),
    sa.Column('activity_fee', sa.Integer(), server_default='0', nullable=True, comment='活动费用'),
    sa.Column('sign_in_radius', sa.Integer(), nullable=True, comment='签到半径，单位公里'),
    sa.Column('sign_in_token', sa.String(length=10), nullable=False, comment='签到口令'),
    sa.Column('theme_pic_name', sa.String(length=300), nullable=False, comment='活动主题图片, 保存路径为/static/activity_theme_picture/*'),
    sa.ForeignKeyConstraint(['admin_raiser'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['approver'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['assignee'], ['user.openid'], ),
    sa.ForeignKeyConstraint(['user_raiser'], ['user.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_participant',
    sa.Column('activity_id', sa.BigInteger(), nullable=False, comment='引用活动ID，关联活动表，进入详情页中的数据库表'),
    sa.Column('participant_openid', sa.String(length=28), nullable=False, comment='参加活动的志愿者或者视障人士ID'),
    sa.Column('interested', sa.Integer(), server_default='0', nullable=True, comment='是否喜欢，将活动标志为喜欢'),
    sa.Column('share', sa.Integer(), server_default='0', nullable=True, comment='分享的次数，一个活动可能会有多次的分享'),
    sa.Column('thumbs_up', sa.Integer(), server_default='0', nullable=True, comment='是否点赞，默认值为0'),
    sa.Column('certificated', sa.Integer(), nullable=True, comment='是否已经获得过证书，0=未获得，1=已获得'),
    sa.Column('certificate_date', sa.DateTime(), nullable=True, comment='获得证书的日期'),
    sa.Column('paper_certificate', sa.Integer(), nullable=True, comment='是否需要纸质证书，0=不需要，1=需要'),
    sa.Column('current_state', sa.String(length=10), nullable=True, comment='状态：Registered, signed_up, signed_off'),
    sa.Column('signup_time', sa.DateTime(), nullable=True, comment='签到时间'),
    sa.Column('signup_latitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='签到经纬度-纬度'),
    sa.Column('signup_longitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='签到经纬度-经度'),
    sa.Column('signoff_time', sa.DateTime(), nullable=True, comment='签退时间'),
    sa.Column('signoff_latitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='签退经纬度-纬度'),
    sa.Column('signoff_longitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='签退经纬度-经度'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['participant_openid'], ['user.openid'], ),
    sa.PrimaryKeyConstraint('activity_id', 'participant_openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_participant')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('pickup_volunteer')
    op.drop_table('pickup_impaired')
    op.drop_table('admin')
    # ### end Alembic commands ###
