"""migration with user_document table.

Revision ID: 0d4b5abd8336
Revises: 186dd5501b6c
Create Date: 2023-07-19 15:42:33.275384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4b5abd8336'
down_revision = '186dd5501b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_signed_urls',
    sa.Column('token', sa.String(length=64), nullable=False, comment='预生成的令牌'),
    sa.Column('openid', sa.String(length=64), nullable=True, comment='令牌授权的用户ID'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='令牌失效的时间'),
    sa.Column('target_openid', sa.String(length=64), nullable=True, comment='令牌对应的授权该用户可以查看的用户的ID'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('user_identity_documents',
    sa.Column('openid', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('id_document_reverse_side_path', sa.String(length=255), nullable=True, comment='用户身份证人像面路径（背面）'),
    sa.Column('id_document_obverse_side_path', sa.String(length=255), nullable=True, comment='用户身份证国徽面路径（正面）'),
    sa.PrimaryKeyConstraint('openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identity_documents')
    op.drop_table('pre_signed_urls')
    # ### end Alembic commands ###
