"""change ActivityParticipant.duty

Revision ID: 5eeed38571a2
Revises: 87976674f07a
Create Date: 2024-09-10 02:25:57.609665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eeed38571a2'
down_revision = '87976674f07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_participant', sa.Column('duties', sa.JSON(), nullable=True, comment='活动中承担的职责, Duty.id列表'))
    op.add_column('activity_participant', sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'))
    op.drop_constraint('activity_participant_ibfk_3', 'activity_participant', type_='foreignkey')
    op.drop_column('activity_participant', 'duty_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_participant', sa.Column('duty_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_foreign_key('activity_participant_ibfk_3', 'activity_participant', 'duty', ['duty_id'], ['id'])
    op.drop_column('activity_participant', 'remark')
    op.drop_column('activity_participant', 'duties')
    # ### end Alembic commands ###
