"""add disabled ID file path

Revision ID: 87976674f07a
Revises: 501e624380a2
Create Date: 2024-09-09 12:53:21.302065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87976674f07a'
down_revision = '501e624380a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled_id_obverse_path', sa.String(length=255), nullable=True, comment='视障人士残疾人证'))
    op.alter_column('pre_signed_urls', 'side',
               existing_type=sa.String(length=16),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled_id_obverse_path')
    op.alter_column('pre_signed_urls', 'side',
               existing_type=sa.String(length=64),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
