"""add Gift.category and User.audit_comment

Revision ID: e1918018f1e6
Revises: 5eeed38571a2
Create Date: 2024-12-15 14:00:41.711775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1918018f1e6'
down_revision = '5eeed38571a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('category', sa.String(length=60), server_default='other', nullable=False))
    op.alter_column('pre_signed_urls', 'side',
               existing_type=mysql.VARCHAR(length=64),
               comment='身份证正/反面 reverse=背面 obverse=正面',
               existing_nullable=False)
    op.add_column('user', sa.Column('audit_comment', sa.String(length=255), server_default='', nullable=False, comment='审核用户注册申请的批注,管理员审核注册用户时更新'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'audit_comment')
    op.alter_column('pre_signed_urls', 'side',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='身份证正/反面 reverse=背面 obverse=正面',
               existing_nullable=False)
    op.drop_column('gift', 'category')
    # ### end Alembic commands ###
