name: Buid and Deploy UI

on:
  push:
    branches: [ frontend_auto_deploy ]
  pull_request:
    branches: [ frontend_auto_deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          USERNAME: ${{ secrets.TEST_USERNAME }}
          KEY: ${{ secrets.TEST_SSHKEY }}
          command_timeout: 20m
          PORT: ${{ secrets.TEST_PORT }}
          script: |
            cd /opt/frontend/Grimm/web-admin
            git pull --tags git://github.com/Grimm-Source/Grimm.git frontend_auto_deploy
            docker-compose build 
            docker-compose down
            docker-compose up -d
